---
title: "03-methylkit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# setting up a notbook to run methylkit


https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/060321-oly/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam

/Volumes/block/wd/061421

```{bash}
pwd
```


```{bash}
wget -r \
--no-directories --no-parent \
-P /Volumes/block/wd/061421/ \
--quiet \
-A *deduplicated.sorted.bam \ https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/060321-oly/
```
/Volumes/block/wd/061421/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam

```{r}
sb.list=list('/Volumes/block/wd/061421/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/2_CGATGT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/3_TTAGGC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/4_TGACCA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/5_ACAGTG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/6_GCCAAT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/7_CAGATC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '/Volumes/block/wd/061421/8_ACTTGA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam'
)
```



```{r}
library(methylKit)
```


```{r, eval = FALSE}
myobj_01 = processBismarkAln(location = sb.list, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=2, treatment = c(0,0,0,0,1,1,1,1))
```

```{r}
save(myobj_01, file = "../analyses/myobj_01")
```


```{r}
getMethylationStats(myobj_01[[3]],plot=TRUE,both.strands=FALSE)

```
filtered.myobj

```{r}
getMethylationStats(filtered.myobj[[3]],plot=TRUE,both.strands=FALSE)

```
```{r}
getCoverageStats(filtered.myobj[[2]],plot=TRUE,both.strands=FALSE)

```


```{r}
#load("../analyses/myobj_11")
```

```{r}
filtered.myobj=filterByCoverage(myobj_01,lo.count=10,lo.perc=NULL,
                                      hi.count=1000,hi.perc=NULL)

meth_filter=unite(filtered.myobj, min.per.group=3L, destrand=TRUE)

clusterSamples(meth_filter, dist="correlation", method="ward", plot=TRUE)


PCASamples(meth_filter)

```



```{r}
myDiff=calculateDiffMeth(meth_filter,mc.cores=8)

```




```{r}
# get hyper methylated bases
myDiff25p.hyper=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p.hypo=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p=getMethylDiff(myDiff,difference=10,qvalue=.01)





```




```{r}
head(filtered.myobj)
```

```{r}
getCorrelation(filtered.myobj,plot=TRUE)
```


```{r}
myobj_lowCov = processBismarkAln(sb.list,
           sample.id = list("1","2","3","4","5","6","7","8"),
           assembly="v081",
           treatment = c(0,0,0,0,1,1,1,1),
           context="CpG",
           mincov = 3
           )

```


ocation = sb.list, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=2, treatment = c(0,0,0,0,1,1,1,1))

















```{r}
# Function
tileit <- function(object, win.size=100, step.size=100, cov.bases=5) {
  g.meth <- as(object,"GRanges")
  chrs <- as.character(unique(seqnames(g.meth)))
  grl <- split(g.meth, seqnames(g.meth))
  max.length <- max(end(grl))
  numTiles <- floor((max.length - (win.size - step.size))/step.size) + 1
  starts <- unlist(sapply(numTiles,function(x) 1+0:(x-1)*step.size))
  ranges <- IRanges(start=starts, width=rep(win.size,length(starts)))
  all.wins <- GRanges(seqnames=Rle(chrs, numTiles), ranges=ranges)
  rcounts <- regionCounts(object, all.wins, 0, strand.aware=FALSE)
  rcounts.filtered <- rcounts[rcounts$coverage >= cov.bases, ]
  return(rcounts.filtered)
}

# Code to run function on methylKitList
new.list <- lapply(myobj_01, tileit)
myobj.tiled <- new("methylRawList", new.list, treatment=myobj_01@treatment)
```


```{r}
filtered.myobj_tile=filterByCoverage(myobj.tiled,lo.count=5,lo.perc=NULL,
                                      hi.count=100,hi.perc=NULL)

meth_filter_tile=unite(filtered.myobj_tile, destrand=TRUE)

clusterSamples(meth_filter_tile, dist="correlation", method="ward", plot=TRUE)


PCASamples(meth_filter_tile,screeplot=FALSE, adj.lim=c(0.0004,0.1),
           scale=TRUE,center=TRUE,comp=c(1,2),transpose=TRUE,sd.filter=TRUE,
           sd.threshold=0.5,filterByQuantile=TRUE,obj.return=FALSE)


```




```{r}
myDiff_tile=calculateDiffMeth(meth_filter_tile,mc.cores=4)

```


```{r}
# get hyper methylated bases
myDiff25p.hyper=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p.hypo=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p=getMethylDiff(myDiff,difference=25,qvalue=0.01)





```


```{r}
# get hyper methylated bases
myDiff25p_t.hyper=getMethylDiff(myDiff_tile,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p_t.hypo=getMethylDiff(myDiff_tile,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p_t=getMethylDiff(myDiff_tile,difference=25,qvalue=0.01)





```




```{r}
write.table(myDiff25p, file = "../analyses/myDiff25p.tab", sep = "\t")
```


