---
title: "20-SpurSupp-tables"
output: html_document
---


running wiht annotation v1.3

```{r}
library(tidyverse)
```

```{r}
S3 <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S3_ Morula_Cluster16.txt", header = TRUE, sep="\t") 
```


```{r}
top1.3 <- read.csv("../analyses/top.annotv1.3.tab", header = TRUE, sep="\t")
```






```{r}
S3_top1.3 <-left_join(S3, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S3_top1.3,
  "../analyses/S3_top1.3.tsv"
)

```


S4

```{r}
S4 <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S4_ Morula_Cluster20.txt", header = TRUE, sep="\t") 
```



```{r}
S4_top1.3 <-left_join(S4, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S4_top1.3,
  "../analyses/S4_top1.3.tsv"
)

```


S7_morula


```{r}
S7mor <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_morula.txt", header = TRUE, sep="\t") 
```



```{r}
S7mor_top1.3 <- left_join(S7mor, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7mor_top1.3,
  "../analyses/S7mor_top1.3.tsv"
)

```


S7_eb early blastula


```{r}
S7eb <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_early_blastula.txt", header = TRUE, sep="\t") 
```



```{r}
S7eb_top1.3 <- left_join(S7eb, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7eb_top1.3,
  "../analyses/S7eb_top1.3.tsv"
)

```


S7_hb  hatched blastula


```{r}
S7hb <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_hatched_blastula.txt", header = TRUE, sep="\t") 
```



```{r}
S7hb_top1.3 <- left_join(S7hb, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7hb_top1.3,
  "../analyses/S7hb_top1.3.tsv"
)

```



S7_mb mesenchyme blastula


```{r}
S7mb <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_mesenchyme_blastula.txt", header = TRUE, sep="\t") 
```



```{r}
S7mb_top1.3 <- left_join(S7mb, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7mb_top1.3,
  "../analyses/S7mb_top1.3.tsv"
)

```


S7_eg early gastrula


```{r}
S7eg <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_early_gastrula.txt", header = TRUE, sep="\t") 
```



```{r}
S7eg_top1.3 <- left_join(S7eg, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7eg_top1.3,
  "../analyses/S7eg_top1.3.tsv"
)

```




S7_lg late gastrula


```{r}
S7lg <- read.csv("../data/fwddev191528revisedsupplementaryfile/Table S7_ Cluster 20 Markers_Late_gastrula.txt", header = TRUE, sep="\t") 
```



```{r}
S7lg_top1.3 <- left_join(S7lg, top1.3, by = c("Row.names" ="sp_sym"))
```


```{r}
write_tsv(
  S7lg_top1.3,
  "../analyses/S7lg_top1.3.tsv"
)

```

