---
title: "60-allgig-methylkit"
output: github_document
---


```{r}
library(methylKit)
```

```{bash}
wget -r \
--no-check-certificate \
--quiet \
--no-directories --no-parent \
-P /media/1TB_ext_SSD01/sr320/wd/ \
-A *sorted.bam \
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/061021-big/
```

```{r}
file.list_allgig=list('/media/1TB_ext_SSD01/sr320/wd/0501_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/0502_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/0503_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/3501_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/3502_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/3503_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5201_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5202_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5203_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5901_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5902_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/5903_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_10_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_1_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_2_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_3_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_4_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_5_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_6_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_7_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_8_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3534_9_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_10_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_11_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_12_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_13_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_14_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_15_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_16_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_17_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_18_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_19_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_1_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_20_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_21_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_22_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_23_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_24_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_2_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_3_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_4_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_5_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_6_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_7_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_8_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zr3644_9_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_1_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_2_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_3_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_4_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_5_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_6_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_7_R1_bismark_bt2_pe.deduplicated.sorted.bam',
                '/media/1TB_ext_SSD01/sr320/wd/zrtg3616_8_R1_bismark_bt2_pe.deduplicated.sorted.bam'
)
```

```{r eval=FALSE, include=FALSE}
myobj_all = processBismarkAln(location = file.list_allgig,
  sample.id = list("0501","0502","0503","3501","3501","3502","3503","5901", "5902","5903","39F","3F","41F","44F","48F","50F","52F","53F","54F","59M","64M","6M","76F", "77F","7M","9M"),
  assembly = "cv",
  read.context="CpG",
  mincov=2,
  treatment = c(3,1,2,2,4,3,4,3,4,4,2,4,4,2,3,4,2,2,2,3,1,1,2,4,1,3))
```